### PR TITLE
Minor changes in storebuttons

### PR DESCRIPTION
**Pull request by Dibyendu303**
Minor changes in storebutton-apple-lightmode and storebutton-amazon-lightmode.
1. Changed the padding
2. Adjusted the icon and font size as per the Figma file

Attached screenshots:

## Before:
Screenshot (2096)
Screenshot (2097)

## After:
Screenshot (2103)
Screenshot (2104)

### CODE REVIEW

**Comment by Rajdip019** [comment]
Are those two buttons are of same size?

**Comment by Dibyendu303** [comment]
@Rajdip019  The length of the "App store" button is just a little less. Do we need them to be of the same length ?

**Comment by Rajdip019** [comment]
If you are working on the store buttons make all the same length that will be consistent I guess. @Dibyendu303

**Comment by Dibyendu303** [comment]
Okay, I will update all the buttons

**Comment by Dibyendu303** [comment]
@Rajdip019 updated the size of all the buttons.

Also minor design changes in the following buttons:
## Before:
Screenshot (2111)
Screenshot (2112)

## After:
Screenshot (2114)
Screenshot (2113)

**Comment by Rajdip019** [comment]
Great work @Dibyendu303

**Pull request merged**
