### PR TITLE
Create product-card-3-blue.html

### PR DESCRIPTION
**Pull request by himanshu1221**
Screenshot from 2023-02-18 14-58-15

### CODE REVIEW

**Comment by himanshu1221** [comment]
> @himanshu1221 Please make the component of fixed width as it is shown in figma design and responsive too.

sure I'll look into it

**Comment by himanshu1221** [comment]
hey ! @RavindraP04 i have made some changes could you please review them

**Comment by RavindraP04** [comment]
Congrats @himanshu1221 🎉, your PR got merged. To be eligible for the swags from ClueLess.

Don’t forget to star this repository. ⭐

**Comment by himanshu1221** [comment]
> Congrats @himanshu1221 tada, your PR got merged. To be eligible for the swags from ClueLess.
> 
> Don’t forget to star this repository. star

thanks @RavindraP04 :partying_face:

**Pull request merged**
