### PR TITLE
Added a feedback form(feedback-1.html)

### PR DESCRIPTION
**Pull request by G0V1NDK**
Final screenshot
image

### CODE REVIEW

**Comment by Rajdip019** [comment]
Remove all the `.DS_Store` files. The PR should show only one file change. @G0V1NDK

**Comment by G0V1NDK** [comment]
Can I add a .gitignore file globally to ignore the .DS_Store file?

**Comment by Rajdip019** [comment]
Yeah do that. As well add `.vscode` also in the list. @G0V1NDK

**Comment by G0V1NDK** [comment]
@Rajdip019 done the required changes. You can check them.

**Comment by Rajdip019** [comment]
Nice work. @G0V1NDK

**Comment by G0V1NDK** [comment]
Thanks, @Rajdip019

**Pull request merged**
