### PR TITLE
Overlay Image Effect

### PR DESCRIPTION
**Pull request by Kumar-Ankit56**
#721 successfully resolve 

Please review and merged
 
final output like this 

https://play.tailwindcss.com/cCoFU4F19w?file=config

### CODE REVIEW

**Comment by Rajdip019** [comment]
There are some things we need to change. Like `rounded-2xl` also while hover. 

Use the button component form our Button library.

Also follow the content card design system and make text and padding and all other changes according to that. @Kumar-Ankit56

**Comment by Kumar-Ankit56** [comment]
> There are some things we need to change. Like `rounded-2xl` also while hover.
> 
> Use the button component form our Button library.
> 
> Also follow the content card design system and make text and padding and all other changes according to that. @Kumar-Ankit56

@Rajdip019 I have follow all the changes that you suggested and I also used existing component from reop. Please have  a look  else I can add more or it's fine
https://play.tailwindcss.com/zi9QU2eHBR

**Comment by Kumar-Ankit56** [comment]
> There are some things we need to change. Like `rounded-2xl` also while hover.
> 
> Use the button component form our Button library.
> 
> Also follow the content card design system and make text and padding and all other changes according to that. @Kumar-Ankit56

@Rajdip019 I have follow all the changes that you suggested and I also used existing component from reop. Please have  a look  else I can add more or it's fine

https://play.tailwindcss.com/kqXtDDKihj

**Comment by Rajdip019** [comment]
Looks really good now. @Kumar-Ankit56

**Pull request merged**
