### PR TITLE
Issue 2231 : Add Mobile Navbar in website - fixed

### PR DESCRIPTION
**Pull request by mani200307**
Fixed - Added hamburger icon and its functionality when screen size is reduced to mobile version.

### CODE REVIEW

**Comment by RavindraP04** [comment]
@mani200307 
This one does not looks good
Can you make it like the one in https://clueless.live website
image
image

**Comment by mani200307** [comment]
Sure thanks.

**Comment by mani200307** [comment]
image

I have made the changes and commited the code. But, It shows the code is not deployed. But, It works fine in my localhost.

**Comment by RavindraP04** [comment]
@Rajdip019, Can you please tell, what is the deployment error in this ?

**Comment by RavindraP04** [comment]
Hey @mani200307

**Comment by mani200307** [comment]
Sure, I'll make the change

**Comment by mani200307** [comment]
Thanks @RavindraP04 , I fixed the issue. Now it is deployed!

**Comment by RavindraP04** [comment]
Great @mani200307,
Just fix this one 
Make the logo Size and Seamless UI text size Small

image

**Comment by mani200307** [comment]
Sure, I'll do the fix

**Comment by mani200307** [comment]
@RavindraP04, Now I've fixed the issue with respect to alignment. I hope it looks good now.

**Pull request merged**
