### PR TITLE
Create content-card-11-white.html

### LINKED ISSUE #1783: Create content card 11 white
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
image

Follow  [figma design](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=qRahoepdI3B98cVA-1) and to make the button use [Button Design System](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) 

After building the component please raise a PR with a screenshot of the component and add the component in `Content Cards/src/content-card-11-white.html`.
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

### PR DESCRIPTION
**Pull request by prafulbbandre**
closes #1783 
Screenshot (34)

### CODE REVIEW

**Comment by RavindraP04** [comment]
@prafulbbandre Make it mobile responsive too.

**Comment by prafulbbandre** [comment]
@RavindraP04 sure

**Comment by prafulbbandre** [comment]
**Changes made**
Screenshot (38)

**Comment by prafulbbandre** [comment]
Proof:

https://user-images.githubusercontent.com/109658545/226992781-fd4d678c-a695-47da-83dc-858aab9dfcc4.mp4

**Comment by RavindraP04** [comment]
@prafulbbandre Please use only tailwind css to make it responsive and not media quries, You can refer to the exixting components in the repo, I'll also share the link on the same.

**Pull request merged**
