### PR TITLE
Create checkbox Black #1988, Solved

### PR DESCRIPTION
**Pull request by neokd**

### CODE REVIEW

**Comment by RavindraP04** [comment]
@neokd See the on checked state in this and make the the checked state like in this one https://github.com/Clueless-Community/seamless-ui/blob/main/Form/src/radio-button-black.html

**Comment by neokd** [comment]
I'll correct it and update you

**Comment by neokd** [comment]
@RavindraP04 updated!

**Comment by RavindraP04** [comment]
@neokd the main tick symbol or check symbol is not visible on checked state, make it like when the box is checked backgroud turns slate 900 but has white tick symbol too.

**Comment by neokd** [comment]
Done @RavindraP04

**Comment by RavindraP04** [comment]
@neokd 
image
for all the checkbox border radius should be rounded
For the 1st checbox:- border should be gray-300, background should be slate-900, on checked: also bg-slate-900  and white tick
For the 2nd checbox:- border should be slate-900, background should be white, on checked: bg-slate-900  and white tick
For the 3rd checbox:- border should be white, background should white, on checked: bg-slate-900  and white tick
For the 4th checbox:- border should be gray-300, background should be gray-300, on checked: bg-slate-900  and disabled

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC

**Comment by RavindraP04** [comment]
Congrats @neokd 🎉, your PR got merged. To be eligible for the swags from ClueLess.

Don’t forget to star this repository. ⭐

**Pull request merged**
