### PR TITLE
improved breadcrumb

### LINKED ISSUE #2071: Improve Breadcrumb
Need to improve this component on `Breadcrumb/src/Breadcrumb.html`

## Improvements required :
Make working Breadcrumb i.e. when the user clicks on any menu[Dashboard, Components, Breadcrumbs], the bg color of that particular menu should change to blue-600 and text white and only one menu can remain active at a time, By active I mean only one option in the breadcrumb should have bg-blue-600 and text-white when it is clicked and others should be in their default state

## Any reference image?
image
  
You can checkout [this](https://github.com/Clueless-Community/seamless-ui/blob/main/Breadcrumb/src/Breadcumb.html) one for better understanding.

### PR DESCRIPTION
**Pull request by Awesomeasma**
closes #2071 

breadcrumb

### CODE REVIEW

**Comment by RavindraP04** [comment]
@Awesomeasma You have to do it without using script, only using HTML and Tailwind CSS

**Comment by Awesomeasma** [comment]
Ok sir 

> @Awesomeasma You have to do it without using script, only using HTML and Tailwind CSS

**Comment by Awesomeasma** [comment]
> @Awesomeasma You have to do it without using script, only using HTML and Tailwind CSS

@RavindraP04 
Am i allowed to use some basic CSS ?

**Comment by Awesomeasma** [comment]
breadcrumb-updated

**Comment by RavindraP04** [comment]
> > @Awesomeasma You have to do it without using script, only using HTML and Tailwind CSS
> 
> @RavindraP04 Am i allowed to use some basic CSS ?

No, Use only Pure Tailwind CSS

**Comment by RavindraP04** [comment]
@Awesomeasma Please do not remove gray bg and border radius of those bg
https://user-images.githubusercontent.com/98400348/224539661-d56d8faf-8656-4484-ba0b-4f601786cc5f.png

**Comment by Awesomeasma** [comment]
ok sir, I will update it right away.

> @Awesomeasma Please do not remove gray bg and border radius of those bg https://user-images.githubusercontent.com/98400348/224539661-d56d8faf-8656-4484-ba0b-4f601786cc5f.png

**Comment by Awesomeasma** [comment]
breadcrumb-final

**Comment by Awesomeasma** [comment]
@RavindraP04 
Please review it.

**Comment by Awesomeasma** [comment]
Is this ok ??

**Comment by Awesomeasma** [comment]
I made it according to the image that u provided.

**Comment by Awesomeasma** [comment]
@RavindraP04 
Please review it..

**Comment by RavindraP04** [comment]
@Awesomeasma I gave the wrong link on the image, can you please make it like this [image](https://user-images.githubusercontent.com/98400348/224540300-eada41c9-977d-4391-81c8-132a26d18deb.png)

**Comment by Awesomeasma** [comment]
@RavindraP04 
I just noticed that the image u provided, belonged to the other issue, may i push these changes to that issue and remake this one ??

**Comment by Awesomeasma** [comment]
As i have already made this component..please ? 

> @RavindraP04 I just noticed that the image u provided, belonged to the other issue, may i push these changes to that issue and remake this one ??

**Comment by Awesomeasma** [comment]
breadcrumb

**Comment by Awesomeasma** [comment]
> @RavindraP04 I just noticed that the image u provided, belonged to the other issue, may i push these changes to that issue and remake this one ??

I made efforts to make that..

**Pull request merged**
