### PR TITLE
message-textarea-rounded-white file added

### PR DESCRIPTION
**Pull request by SudiptaSaha123**
Here is the component I have built. 

Here is a screenshot of that.

message

### CODE REVIEW

**Comment by RavindraP04** [comment]
@SudiptaSaha123 Please do not Make a PR until the issue is assigned to you But for this one 
Give padding and use textarea and do not use arbitrary values instead use default or closest tailwind classes

**Comment by SudiptaSaha123** [comment]
ok

**Comment by SudiptaSaha123** [comment]
I have updated the code with textarea. Please check

**Comment by RavindraP04** [comment]
@SudiptaSaha123 Can you make it responsive too ?

**Pull request closed without merging**
