### PR TITLE
Fixed Product Section

### LINKED ISSUE #2238: [WEBSITE] - Fix Product Section
# Fix Product Section mobile screen (360px)
- Fix Text Size 
- Give px as shown below 

## Instructions 
- You can get the code of the website in `website-dev` branch 
- After making changes, Push the changes to `website-dev` branch 
- You will find the code of this components [here](https://github.com/Clueless-Community/seamless-ui/blob/website-dev/components/Product.tsx)
- For the mobile screen change the size of image in the card at 360px 👇

### PR DESCRIPTION
**Pull request by codescalper**
**Title:** Update text styles in Product.tsx

**Description:**
This PR updates the text styles of the website. Specifically, it reduces the size of the main header and adds padding to the description paragraph to improve readability.

**Changes Made:**
- Updated main header text size to 3xl
- Added left padding to description paragraph

**Reason for Changes:**
The previous styles were making the text difficult to read on smaller screens, so I made these changes to improve the overall user experience. 

Fixes #2238

### CODE REVIEW

**Comment by RavindraP04** [comment]
Hey @codescalper 

The font size of main heading for Large screen was ok but I think you have changed it a bit, so make it like it was earlier, For reference you can see that here https://seamlessui.vercel.app/

also the Visit Clueless Button is not aligned properly  with the above text


Screenshot 2023-05-16 214030

Also the image is become very small for tab size screen 
image

**Comment by codescalper** [comment]
Didn't see it on the larger px will fix it :)

**Comment by codescalper** [comment]
Hey @RavindraP04 made this changes, 
1. Heading Update:
   - Reduced the font size of the heading to 3xl on mobile screens (360px).
   - Added left and right padding of 4px to provide better spacing.

2. Paragraph Update:
   - Increased the font size of the paragraph to xl on mobile screens (360px).
   - Added left and right padding of 5px to improve readability.
   
   Here's how it looks 
   

https://github.com/Clueless-Community/seamless-ui/assets/92156721/23ac7849-b51a-43de-a9a0-67b9ce6c9030


   WIll commit the changes, want some confirmation from you

**Comment by RavindraP04** [comment]
@codescalper look good! Commit the changes and I'll merge it.

**Comment by codescalper** [comment]
> @codescalper look good! Commit the changes and I'll merge it.

Done!

**Pull request merged**
