### PR TITLE
Create timeline-2.html

### PR DESCRIPTION
**Pull request by nik132-eng**
https://play.tailwindcss.com/JgrQ0upFEH

image

#800

### CODE REVIEW

**Comment by Rajdip019** [comment]
Follow our design system. Like the colors boreder radius. Like the shadow color on the hover. Fix them and tag me again after the changes. @nik132-eng

**Comment by Rajdip019** [comment]
Make the text white. And the shadow still needs to be fixed. Don't give shadow or go with a subtle shadow. @nik132-eng

**Comment by nik132-eng** [comment]
https://play.tailwindcss.com/6dNPZ6KXdo

image

as you said?

**Comment by Rajdip019** [comment]
Looks good. @nik132-eng

**Pull request merged**
