### PR TITLE
Create feature-card-22.html

### PR DESCRIPTION
**Pull request by nik132-eng**
https://play.tailwindcss.com/NK5EDbm67i

image

#836

### CODE REVIEW

**Comment by Rajdip019** [comment]
Follow the design system. Make sure to use the color we are using. Like the button. Use the buttons - icon button and the normal button from the Buttons folder and ratings from the ratings folder of this repo only. 

Have border-radius-2xl and also please the Design system. After doing this tag me here.

Also remove all the bg image an back round colors. Remove the `style` tag.

@nik132-eng

**Comment by nik132-eng** [comment]
ok

**Comment by nik132-eng** [comment]
https://play.tailwindcss.com/WqAqo5OtnI

image

**Comment by Rajdip019** [comment]
The icon button as well change it.

**Comment by nik132-eng** [comment]
image

this one?

**Comment by Rajdip019** [comment]
Yes the edit button. @nik132-eng

**Comment by Rajdip019** [comment]
Resolve the conflicts and then everything will be good to merge I guess.

**Comment by nik132-eng** [comment]
image

**Comment by nik132-eng** [comment]
> Resolve the conflicts and then everything will be good to
can you help me how to do resolve conflicts? can you share any resources if you have

**Comment by nik132-eng** [comment]
make new PR for this

**Pull request closed without merging**
