### PR TITLE
Update `Buttons/README.md`

### PR DESCRIPTION
**Pull request by sarkartanmay393**
#### Changes Made 

image_16x9 (12)

#### Will it work @RavindraP04 ?  
.

### CODE REVIEW

**Comment by RavindraP04** [comment]
@sarkartanmay393 The height of each button in the screenshot is same like height of small, medium and large button is same 
Make a div with flex h-screen items-center justify-center gap-5 and then take the screenshot 
https://play.tailwindcss.com/12CuFx59z4

**Comment by sarkartanmay393** [comment]
> @sarkartanmay393 The height of each button in the screenshot is same like height of small, medium and large button is same 
> Make a div with flex h-screen items-center justify-center gap-5 and then paste the code of the component in this div and then take the screenshot
> https://play.tailwindcss.com/12CuFx59z4

Yeh, I did it in a similar way. It will work right?

**Comment by RavindraP04** [comment]
@sarkartanmay393 Just see the difference of the component in your screenshot and in my screenshot
image

This is how the Buttons shoudl look link in the screenshot 👇
image

**Comment by sarkartanmay393** [comment]
@RavindraP04 It's done ✅

**Waiting for Review**

**Comment by RavindraP04** [comment]
Congrats @sarkartanmay393 🎉, your PR got merged. To be eligible for the swags from ClueLess. 

Don’t forget to star this repository. ⭐

**Pull request merged**
