### PR TITLE
store-button-windows-white

### LINKED ISSUE #1962: Create a Store Button Windows White
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
image

After building the component please raise a PR with a screenshot of the component and add the component in `Store Buttons/src/store-button-windows-lightmode.html` and rename the file to `store-button-windows-white.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

### PR DESCRIPTION
**Pull request by SHYALI**
closes #1962
button

### CODE REVIEW

**Comment by SHYALI** [comment]
Is there any problem with the commit? 
@RavindraP04 guide me, I will change it as per requirement.

**Comment by RavindraP04** [comment]
@SHYALI just remove the outermost div

**Comment by SHYALI** [comment]
@RavindraP04 updated!

**Comment by RavindraP04** [comment]
From next PR just mention this 
`closes #id_of_Issue`
By this way the issue will be automatically closed once the PR has been merged

**Comment by SHYALI** [comment]
okay ,sure

**Pull request merged**
