### PR TITLE
Added content card 13 black

### PR DESCRIPTION
**Pull request by AshutoshSingh2021**
#Description
Added the content card 13 black 
 
fixes(#1789)

Screenshot (185)

### CODE REVIEW

**Comment by AshutoshSingh2021** [comment]
@RavindraP04  I have created the content card 13 black please review my PR.

**Comment by RavindraP04** [comment]
Can you please make it using Video tag of HTML

**Comment by AshutoshSingh2021** [comment]
yeah sure.

**Comment by AshutoshSingh2021** [comment]
@RavindraP04 I tried creating it using Video tag but I am not getting it right, please guide me further. Can you please provide me with some resources? And I have modified the previous code and made it a bit cleaner.

**Pull request closed without merging**
