### PR TITLE
Improved marketplace-product-3

### LINKED ISSUE #1040: Improve marketplace-product-3
Need to improve this component: marketplace-product-3

## Improvements required :
Blue circle doesn't change on clicking

## Any reference image?
Screenshot (2134)

### PR DESCRIPTION
**Pull request by Dibyendu303**
Closes #1040 . Improved marketplace-product-3. Attached screenshots:

Screenshot (2147)

### CODE REVIEW

**Comment by Dibyendu303** [comment]
@Rajdip019 This one is implemented as radio.

**Comment by RavindraP04** [comment]
Would suggest you to make this also as checkbox, so that filtering for more than one can be done easily .

**Comment by Rajdip019** [comment]
Make this a checkbox @Dibyendu303

**Comment by Dibyendu303** [comment]
Updated now @Rajdip019

**Pull request merged**
