### PR TITLE
Product card Readme updated

### PR DESCRIPTION
**Pull request by Laxmankohar**
Closes: #2050 
image

### CODE REVIEW

**Comment by RavindraP04** [comment]
@Laxmankohar For product card 3 and product card 4[all three variants] keep the screenshot orientation of these components horizontal

**Comment by Laxmankohar** [comment]
> @Laxmankohar For product card 3 and product card 4[all three variants] keep the screenshot orientation of these components horizontal as it is in [figma design](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=dJ7lZ2X7J03zpqwy-0)

Okk. Can you help me out to change orientation

**Comment by Laxmankohar** [comment]
image

**Comment by RavindraP04** [comment]
Congrats @Laxmankohar 🎉, your PR got merged. To be eligible for the swags from ClueLess. 

Don’t forget to star this repository. ⭐

**Pull request merged**
