### PR TITLE
Time Section Aligned correctly 

### LINKED ISSUE #2279: Time Section Not Aligned correctly
## Current behavior

The `Web.tsx` section and the `Time.tsx` section is not aligned properly because of which the page is overflowing in x axis 
This issue is happening between the `lg` to `xl` breakpoint

## Sample Images

image

image

### Time section is Overlapping with its text
image

### PR DESCRIPTION
**Pull request by Mehaksharma6**
closes #2279

The issue was in the `Time.tsx` section mainly with the timeline graph, below I have attached the before and after images 

## Before
image

## After

image
## Before
image

## After
image

## Before
image

## After
image

### CODE REVIEW

**Comment by Mehaksharma6** [comment]
@RavindraP04 Please review this PR

**Comment by RavindraP04** [comment]
Can you shift the image a little bit downwards @Mehaksharma6 , it looking cluttered near about 768px
image

**Comment by Mehaksharma6** [comment]
Sure, I can do that

**Comment by Mehaksharma6** [comment]
How is this ?
image

**Comment by RavindraP04** [comment]
This one looks better @Mehaksharma6

**Comment by Mehaksharma6** [comment]
Pushed the changed, Please check @RavindraP04

**Comment by RavindraP04** [comment]
Looks Good, Merging it 

Thanks for your valuable contribution @Mehaksharma6

**Pull request merged**
