### PR TITLE
Created footer-white-14

### PR DESCRIPTION
**Pull request by crveda**
Solved issue number - #507 
ScreenShot

### CODE REVIEW

**Comment by crveda** [comment]
The mobile view is :

**Comment by RavindraP04** [comment]
Give a little dark shade of blue to the big curve, try this #E8EEFA

**Comment by crveda** [comment]
I updated with the suggested color
Could you check this sir ?

**Comment by Rajdip019** [comment]
Looks amazing great work @crveda 

Congrats 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow these steps.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/)
3. Go to the profile section from the top right-hand corner.



Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard!

And don’t forget to share your achievement with your friends.

**Pull request merged**
