### PR TITLE
MovieCard-Componenet.html

### PR DESCRIPTION
**Pull request by Kumar-Ankit56**
#Successfully completed issue no #740

Please check and merged

Final output something like this.

https://play.tailwindcss.com/SqiPHDQYac

### CODE REVIEW

**Comment by Kumar-Ankit56** [comment]
> Make rounded corners. That will go better with design system I guess.

https://play.tailwindcss.com/SqiPHDQYac 

Will it fine as I have given rounded large.

**Comment by Rajdip019** [comment]
Make it 2xl as we are using that everywhere.  @Kumar-Ankit56

**Comment by Kumar-Ankit56** [comment]
> Make it 2xl as we are using that everywhere. @Kumar-Ankit56

@Rajdip019  changes done

**Comment by Rajdip019** [comment]
Great work @Kumar-Ankit56

**Comment by Rajdip019** [comment]
It only works if you hover on the bottom part of the image. But it should be visible while hovering on the whole card. And add some padding below the button as well. @Kumar-Ankit56

**Pull request merged**
